apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nodepod
  name: nodepod
spec:
    configMap:
      name: mycm
  containers:
  - image: samiksha18/webapp
    name: nodepod
    ports: 
      - containerPort: 8080
    resources: {}
  envFrom:
  - configMapRef:
      name: mycm  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}