apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nodepod
  name: nodepod
spec:
  containers:
  - image: samiksha18/webapp
    name: nodepod
    envFrom:
      - configMapRef:
          name: mycm  
    ports: 
      - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}